Space-DF/spacedf-sdk-node

workflow/build.yml

feat(CI): create build file yml

---

README.md
api.doc.md
examples/auth/login.ts
examples/auth/register.ts
examples/console/oauth2.ts
src/core.ts
src/index.ts
src/resource.ts

Update readme and api endpoints

docs: update readme and api endpoints

---

src/resources/auth/auth.ts
src/resources/console/oauth2.ts

fix(type): update auth and oauth2

---

.github/workflows/build.yml
.github/workflows/lint.yml
package.json

ci: add build step

---

README.md
api.doc.md
src/core.ts
src/index.ts
src/resources/auth/auth.ts
src/resources/auth/credentials.ts
src/resources/auth/index.ts
src/resources/auth/space-roles.ts
src/resources/dashboard/dashboards.ts

Add the api key to the header request

feat(auth): add the api key to the header request

---

.github/workflows/publish-package.yml

ci: update publish package

---

package.json

ci: fix publish package

---

src/index.ts
src/resource.ts
src/resources/auth/auth.ts
src/resources/auth/credentials.ts
src/resources/auth/space-policies.ts
src/resources/auth/space-role-users.ts
src/resources/auth/space-roles.ts
src/resources/auth/spaces.ts
src/resources/console/oauth2.ts
src/resources/dashboard/dashboards.ts
src/resources/dashboard/device-states.ts
src/version.ts

fix: update API path

---

api.doc.md
src/index.ts
src/resources/auth/auth.ts
src/resources/auth/index.ts
src/resources/auth/invitation.ts
src/resources/auth/join-space.ts
src/resources/auth/presigned-url.ts
src/resources/auth/space-role-users.ts

- Write the invitation api, join-space, presigned-url
- Update the space role user(put, patch), register with OTP code,

feature: add invitation and space role user

---

src/resources/auth/spaces.ts

fix(space): update type slug name invitation

---

api.doc.md
src/resources/auth/auth.ts

feature: add login google

---

api.doc.md
src/index.ts
src/resources/auth/index.ts
src/resources/auth/join-space.ts
src/resources/auth/spaces.ts

fix: update join space

---

api.doc.md
src/resources/auth/spaces.ts

fix: update invitation space

---

api.doc.md
src/resources/auth/auth.ts

feature: implement forget password

---

api.doc.md
src/resources/auth/auth.ts

fix: update forget password

---

api.doc.md
src/resources/auth/space-role-users.ts

feature: implement default for space

---

api.doc.md
src/resources/auth/auth.ts
src/resources/auth/space-policies.ts
src/resources/auth/space-role-users.ts
src/resources/auth/space-roles.ts
src/resources/auth/spaces.ts

bugfix: add header space name

---

api.doc.md
src/resources/auth/space-policies.ts
src/resources/auth/space-role-users.ts
src/resources/auth/space-roles.ts
src/resources/auth/spaces.ts
src/version.ts

fix: format and fix code

---

api.doc.md
src/index.ts
src/resources/device/index.ts
src/resources/device/trip.ts

Implement get trip feature 
Implement api call to trip api

feat: implement get trip

---

api.doc.md
src/index.ts
src/resources/device/device-spaces.ts
src/resources/device/index.ts

Implement device space feature

feat: get device spaces

---

src/resources/device/device-spaces.ts
src/version.ts

fix: wrong api device path

---

api.doc.md
src/index.ts
src/resources/dashboard/index.ts
src/resources/dashboard/widget.ts
src/version.ts

Add update widget to spacedf sdk

feat: bulk update widgets
